apiVersion: skaffold/v2beta15
kind: Config
metadata:
  name: ouistity
build:
  artifacts:
  - image: shokohsc/ouistity
    docker:
      dockerfile: Dockerfile.dev
    context: .
    sync:
      manual:
      - src: 'src/**/*.js'
        dest: .
      - src: 'src/**/*.vue'
        dest: .
deploy:
  kustomize:
    paths:
      - k8s/base
profiles:
  - name: dev
    activation:
      - command: dev
    build:
      artifacts:
      - image: shokohsc/ouistity
  - name: shokohsc
    build:
      cluster:
        namespace: kaniko
        pullSecretName: kaniko-secret
        dockerConfig:
          # path: ~/.docker/config.json
          secretName: kaniko-secret
      artifacts:
      - image: shokohsc/ouistity
        kaniko:
          dockerfile: Dockerfile.dev
    deploy:
      kustomize:
        paths:
          - k8s/overlays/shokohsc
  - name: prod
    build:
      cluster:
        namespace: kaniko
        pullSecretName: kaniko-secret
        dockerConfig:
          secretName: kaniko-secret
      artifacts:
      - image: shokohsc/ouistity
        kaniko:
          dockerfile: Dockerfile
