imports:
    - { resource: config.yml }

framework:
   validation:
       cache: validator.mapping.cache.apc
   serializer:
       cache: serializer.mapping.cache.apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "php://stderr"
            level: debug
        console:
            type:  console

# Fos Cache Http Bundle
fos_http_cache:
    cache_control:
        defaults:
            overwrite: true
        rules:
            # match everything to set defaults
            -
                match:
                    path: ^/
                headers:
                    overwrite: false
                    cache_control: { public: true, max_age: 900, s_maxage: 900 }

services:
  kernel.listener.api_exception_listener:
    class: Shoko\ApiBundle\EventListener\ApiExceptionListener
    arguments: [@translator]
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
