app:
    path:     /
    defaults: { _controller: ApiBundle:Front:index }

api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /api/

_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"
