app:
    resource: @AppBundle/Controller/
    type:     annotation
    schemes:  [%httpProtocol%]

api:
    resource: @ApiBundle/Controller/
    type:     annotation
    prefix:   /api/
    schemes:  [%httpProtocol%]

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
