parameters:
    marvel_api_client.class: Chadicus\Marvel\Api\Client
    marvel_api_curl_adapter.class: Chadicus\Marvel\Api\CurlAdapter

services:
    marvel_api_curl_adapter:
        class: "%marvel_api_curl_adapter.class%"

    marvel_api_client:
        class: "%marvel_api_client.class%"
        arguments:
            - "%marvel_api_key.private%"
            - "%marvel_api_key.public%"
            - @marvel_api_curl_adapter
