parameters:
    comics_per_page: 20

services:
    app.comic_repository:
        class: Front\AppBundle\Repository\ComicRepository
        arguments: [@marvel_api_client]

    app.serie_repository:
        class: Front\AppBundle\Repository\SerieRepository
        arguments: [@marvel_api_client, "%comics_per_page%"]

    app.creator_repository:
        class: Front\AppBundle\Repository\CreatorRepository
        arguments: [@marvel_api_client, "%comics_per_page%"]

    app.twig.app_twig_extension:
        class: Front\AppBundle\Twig\AppTwigExtension
        tags:
            - { name: twig.extension }
