parameters:
    comics_per_page: 20

services:
    app.comic_repository:
        class: Front\AppBundle\Repository\ComicRepository
        arguments: [@marvel.comics, @marvel.comics_query, %comics_per_page%]

    app.serie_repository:
        class: Front\AppBundle\Repository\SerieRepository
        arguments: [@marvel.series, @marvel.series_query, @marvel.comics, @marvel.comics_query, %comics_per_page%]

    app.creator_repository:
        class: Front\AppBundle\Repository\CreatorRepository
        arguments: [@marvel.creators, @marvel.creators_query, @marvel.comics, @marvel.comics_query, %comics_per_page%]

    app.character_repository:
        class: Front\AppBundle\Repository\CharacterRepository
        arguments: [@marvel.characters, @marvel.characters_query, @marvel.comics, @marvel.comics_query, %comics_per_page%]

    app.event_repository:
        class: Front\AppBundle\Repository\EventRepository
        arguments: [@marvel.events, @marvel.events_query, @marvel.comics, @marvel.comics_query, %comics_per_page%]

    app.twig.app_twig_extension:
        class: Front\AppBundle\Twig\AppTwigExtension
        tags:
            - { name: twig.extension }

    app.comic_exposer:
        class: Front\AppBundle\Service\ComicService\ComicPropertiesExposerService
