---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: bubbles
spec:
  selector:
    matchLabels:
      app: bubbles
  template:
    metadata:
      labels:
        app: bubbles
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: bubbles
          image: shokohsc/bubbles
          env:
            - name: ENV
              value: production
            - name: API_GATEWAY_HOST
              value: api.cluster.local
            - name: USE_SENTRY
              value: "false"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          startupProbe:
            tcpSocket:
              port: http
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            httpGet:
              port: http
              path: /
          resources:
            requests:
              cpu: 10m
              memory: 64M
            limits:
              cpu: 1000m
              memory: 256M
