---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ouistity
spec:
  selector:
    matchLabels:
      app: ouistity
  template:
    metadata:
      labels:
        app: ouistity
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: ouistity
          image: shokohsc/ouistity
          env:
            - name: ENV
              value: development
            - name: API_GATEWAY_HOST
              value: api.cluster.local
            - name: API_GATEWAY_PORT
              value: "80"
            - name: GRAPHQL_GATEWAY_HOST
              value: graphql.cluster.local
            - name: GRAPHQL_GATEWAY_PORT
              value: "80"
            - name: GRAPHQL_CACHE_TTL
              value: "600"
            - name: USE_THUMBOR
              value: "false"
            - name: USE_IMGPROXY
              value: "false"
            - name: INTERNAL_API_GATEWAY_URL
              value: "http://api.moleculer-ouistity.svc.cluster.local:5000"
            - name: USE_SENTRY
              value: "false"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          startupProbe:
            tcpSocket:
              port: http
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            httpGet:
              port: http
              path: /
          resources:
            requests:
              cpu: 10m
              memory: 64M
            limits:
              cpu: 100m
              memory: 64M
