---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ouistity
spec:
  selector:
    matchLabels:
      app: ouistity
  template:
    metadata:
      labels:
        app: ouistity
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: ouistity
          image: shokohsc/ouistity
          env:
            - name: ENV
              value: production
            - name: BASE_HOST
              value: localhost
            - name: BASE_PORT
              value: "80"
            - name: API_GATEWAY_HOST
              value: api.cluster.local
            - name: API_GATEWAY_PORT
              value: "80"
            - name: GRAPHQL_GATEWAY_HOST
              value: graphql.cluster.local
            - name: GRAPHQL_GATEWAY_PORT
              value: "80"
            - name: USE_THUMBOR
              value: "false"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
