---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ouistity
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: ca-cluster-issuer
    forecastle.stakater.com/expose: "true"
    forecastle.stakater.com/group: dev
    forecastle.stakater.com/appName: ouistity
spec:
  rules:
  - host: ouistity.shokohsc.home
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ouistity
            port:
              number: 80
  # - host: dev.ouistity.shokohsc.home
  #   http:
  #     paths:
  #     - path: /
  #       pathType: Prefix
  #       backend:
  #         service:
  #           name: ouistity
  #           port:
  #             number: 3000
  # - host: browsersync.ouistity.shokohsc.home
  #   http:
  #     paths:
  #     - path: /
  #       pathType: Prefix
  #       backend:
  #         service:
  #           name: ouistity
  #           port:
  #             number: 3002
  tls:
  - hosts:
    - ouistity.shokohsc.home
    # - dev.ouistity.shokohsc.home
    # - browsersync.ouistity.shokohsc.home
    secretName: ouistity-cert
