apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ouistity
bases:
  - ../../base
  # - imgproxy.yaml
  # - thumbor.yaml
patchesStrategicMerge:
  - ingress.yaml
  - deployment.yaml
  # - service.yaml
